### ISSUE TITLE
Implementation of external requests

### ISSUE THREAD

**Issue by entermix** [kohana/minion#118]
Hello everybody! When the external request, for example:

`$request = Request::factory('http://example.com/post_api')
->method(Request::POST)
->post(array('foo' => 'bar', 'bar' => 'baz'));`

I get an error:

`Request_Exception [ 0 ]: Error fetching remote /sys/send.php [ status 0 ] Failure when receiving data from the peer ~ SYSPATH/classes/Kohana/Request/Client/Curl.php [ 102 ]`

Why is that? file_get_contents () function works without problems

**Comment by shadowhand** [comment]
This project is for minion, which deals with creating command line jobs. Issues regarding Kohana core classes should be reported at https://github.com/kohana/core

Also I would recommend using [Guzzle](http://docs.guzzlephp.org/en/latest/) instead of Kohana's CURL implementation, which is not terribly robust.
