### ISSUE TITLE
Use STDOUT instead of echo

### ISSUE THREAD

**Issue by zeelot** [kohana/minion#14]
I think STDIN/STDOUT/STDERR are the conventions for input and output when working with CLI.

`fwrite(STDOUT, "Some output\n");`

This tutorial seems pretty decent and has some reasons to use STROUT instead of `echo`: http://articles.sitepoint.com/article/php-command-line-1
What do you guys think?

**Comment by BRMatt** [comment]
I agree that echo isn't ideal, I've only been using it as a temporary solution and intend to implement some kind of logging agent (see #5) so that

a) Tasks can provide feedback while they're running (i.e. print a migration's name as soon as it's finished)
b) It would make it easier to run tasks programatically & record their output

**Comment by kiall** [comment]
instead of fwrite(STDOUT, ..) etc ..

http://kohanaframework.org/guide/api/Kohana_Log_StdOut
http://kohanaframework.org/guide/api/Kohana_Log_StdErr

**Comment by BRMatt** [comment]
Closing this in favour of #5

**Comment by BRMatt** [comment]
See [:feature/5-logging-agent](https://github.com/kohana-minion/core/tree/feature/5-logging-agent) for a rough implementation
